/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_agripath_acpcommon_utils_KMeansClusterUtil */

#ifndef _Included_com_agripath_acpcommon_utils_KMeansClusterUtil
#define _Included_com_agripath_acpcommon_utils_KMeansClusterUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_agripath_acpcommon_utils_KMeansClusterUtil
 * Method:    kMeans
 * Signature: (IIIIII[[I)[[[I
 */
JNIEXPORT jobjectArray JNICALL Java_com_agripath_acpcommon_utils_KMeansClusterUtil_kMeans
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
